# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movies.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmovies.proto\"\x1b\n\nMovieEntry\x12\r\n\x05title\x18\x01 \x01(\t\"\x12\n\x10\x41llMoviesRequest\"0\n\x11\x41llMoviesResponse\x12\x1b\n\x06movies\x18\x01 \x03(\x0b\x32\x0b.MovieEntry2F\n\tAllMovies\x12\x39\n\x0eget_all_movies\x12\x11.AllMoviesRequest\x1a\x12.AllMoviesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movies_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MOVIEENTRY']._serialized_start=16
  _globals['_MOVIEENTRY']._serialized_end=43
  _globals['_ALLMOVIESREQUEST']._serialized_start=45
  _globals['_ALLMOVIESREQUEST']._serialized_end=63
  _globals['_ALLMOVIESRESPONSE']._serialized_start=65
  _globals['_ALLMOVIESRESPONSE']._serialized_end=113
  _globals['_ALLMOVIES']._serialized_start=115
  _globals['_ALLMOVIES']._serialized_end=185
# @@protoc_insertion_point(module_scope)
