# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import movies_pb2 as movies__pb2


class AllMoviesStub(object):
    """Movies service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_all_movies = channel.unary_unary(
                '/AllMovies/get_all_movies',
                request_serializer=movies__pb2.AllMoviesRequest.SerializeToString,
                response_deserializer=movies__pb2.AllMoviesResponse.FromString,
                )


class AllMoviesServicer(object):
    """Movies service
    """

    def get_all_movies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AllMoviesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_all_movies': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all_movies,
                    request_deserializer=movies__pb2.AllMoviesRequest.FromString,
                    response_serializer=movies__pb2.AllMoviesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AllMovies', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AllMovies(object):
    """Movies service
    """

    @staticmethod
    def get_all_movies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AllMovies/get_all_movies',
            movies__pb2.AllMoviesRequest.SerializeToString,
            movies__pb2.AllMoviesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
