# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: basics.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62\x61sics.proto\"*\n\rPersonRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"!\n\x0ePersonResponse\x12\x0f\n\x07message\x18\x01 \x01(\t28\n\x07Greeter\x12-\n\x08SayHello\x12\x0e.PersonRequest\x1a\x0f.PersonResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'basics_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PERSONREQUEST']._serialized_start=16
  _globals['_PERSONREQUEST']._serialized_end=58
  _globals['_PERSONRESPONSE']._serialized_start=60
  _globals['_PERSONRESPONSE']._serialized_end=93
  _globals['_GREETER']._serialized_start=95
  _globals['_GREETER']._serialized_end=151
# @@protoc_insertion_point(module_scope)
